### ISSUE TITLE
Use package revisions

### ISSUE THREAD

**Issue by mauriciofierrom** [mauriciofierrom/dialogflow-fulfillment#14]
Consider using package revisions instead of bumping the last digit of the version.

Include `x-revision: n` entry in the cabal file.

**Comment by hasufell** [comment]
I would advise against doing revbumps (especially via hackage), because:

1. they are not part of PVP, which poses numerous issues
2. they currently can break freeze files (revisions are not frozen, this will be "fixed" in next cabal, which will also freeze the entire index state... not sure that's a good default, but yeah)
3. distros often have non-trivial issues with this, because they rely on the version (and tarball) to be self-consistent
4. it is potentially hackage-infrastructure specific, if you upload new cabal files via hackage

I'm aware cabal maintainers think different, but the [documentation](https://github.com/haskell-infra/hackage-trustees/blob/master/revisions-information.md) on this is quite one-sided, so it's good to know there are drawbacks.

**Comment by mauriciofierrom** [comment]
Yeah I came across a bunch of Github issues related to them so I was going to research more about it. I think your explanation and the docs suffices. Thank you very much!
